apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ecommerce-namespace
  labels:
    app: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: ecommerce-db
          image: postgres:16
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: "ecommerce_user"

            - name: POSTGRES_PASSWORD
              value: "ExamDB@2026"

            - name: POSTGRES_DB
              value: "ecommerce_db"